### ISSUE TITLE
Feature: Day of Launch

### ISSUE THREAD

**Issue by umangchaudhry** [dsi-principles-prog/midterm-umangchaudhry#1]
In the original dataset, I have date of launch as a column. The second engineered feature that I am adding to this dataset is a column that uses the information given in the date_of_launch column and provides the day of the week the launch took place.

The feature that needs to be created is called dayoflaunch that is a function that takes in the date from the column in as a parameter and uses the lubridate library to output the day of the week (1-7 value for Sunday through Saturday).

Testing the feature: Some of the things that you should test for is that the values that are output as a result of executing the function over the specified column are values between 1 and 7 (days of the week). 

Another test would be to check whether the feature works correctly by testing if the correct day number is output when given today's date. 

Add the tests to 30-feature-engineering as well as 40-modeling while creating the augmented dataframe.

**Comment by lnguyen1021** [comment]
I have created the dayoflaunch function in 30 and added the new feature in a new dataframe in 40 in the dayoflaunch branch. Will be merging to master
